stages:
  - acceptance_test

acceptance_test:
  image: node:lts
  stage: acceptance_test
  script:
  - npm i selenium-webdriver
  - npm uninstall @cucumber/cucumber
  - npm install @cucumber/cucumber
  - npm install
  - npm run test
