stages:
  - acceptance_test

acceptance_test:
  image: node:lts
  stage: acceptance_test
  script:
  - wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
  - sudo apt-get install unzip
  - wget -N http://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip -P ~/Downloads
  - unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
  - sudo mv -f ~/Downloads/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
  - npm i selenium-webdriver
  - npm uninstall @cucumber/cucumber
  - npm install @cucumber/cucumber
  - npm install
  - npm run test
