stages:
  - acceptance_test

acceptance_test:
  image: node:lts
  stage: acceptance_test
  script:
  - apt-get update
  - apt-get install -y xvfb
  - apt-get install -y zip
  - apt-get install -y wget
  - apt-get install -y ca-certificates
  - apt-get install -y libnss3-dev libasound2 libxss1 libappindicator3-1 libindicator7 gconf-service libgconf-2-4 libpango1.0-0 xdg-utils fonts-liberation libgbm1
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb 
  - dpkg -i google-chrome*.deb 
  - rm google-chrome*.deb
  - wget -N http://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - cp chromedriver /usr/bin/google-chrome
  - rm chromedriver_linux64.zip
  - rm chromedriver
  - rm -rf /tmp/.org.chromium.Chromium*
  - npm i chromedriver
  - npm i selenium-webdriver
  - npm uninstall cucumber
  - npm i cucumber
  - npm install
  - npm run test
